name: CodeCoverage

on:
  pull_request:
  push:
    branches:
      - "**" # trigger the workflow on any branch push event
    paths:
      - "**" # trigger the workflow on any file change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven and generate JaCoCo coverage report
        run: mvn clean install -f common/artifact-manager/pom.xml

#      - name: Upload JaCoCo Report
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: coverage-report
#          path: common/artifact-manager/target/site/jacoco/

      - name: Prepair directory structure for deployment
        if: always()
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          mkdir -p ./deploy/${BRANCH_NAME}/common/artifact-manager/target/site/jacoco/ 
          cp -r ./common/artifact-manager/target/site/jacoco/* ./deploy/${BRANCH_NAME}/common/artifact-manager/target/site/jacoco/

      - name: Deploy Report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
