name: Generate Jacoco Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and generate JaCoCo coverage report
        run: mvn test jacoco:report

      - name: Publish JaCoCo Report
        uses: cicirello/jacoco-report@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverage_file: common/artifact-manager/target/site/jacoco/jacoco.xml
