name: Generate Jacoco Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven and generate JaCoCo coverage report
        run: mvn clean install -f common/artifact-manager/pom.xml

      - name: Publish JaCoCo to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: common/artifact-manager/target/site/jacoco/jacoco.xml
          min-coverage-changed-files: 40
          title: Artifact-Manager Code Coverage Report (Changed Files)

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail PR if changed files coverage is less than 40%
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 40.0 }}
        uses: actions/github-script@v6
        with:
          script: |
             core.setFailed('Changed file coverage is less than 40%!')
